[package]
name = "casiros-api-client"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Typed Rust client for the CASIROS REST API"

[dependencies]
casiros-api = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
actix-web = { workspace = true }
casiros-dag = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
